### ISSUE TITLE
Please upload AppImage

### ISSUE THREAD

**Issue by probonopd** [JaviBonilla/surf#1]
https://github.com/JaviBonilla/surf/blob/c791d1c5d4654e3fdcd2b4eab36cff83c4372895/build/build_surf_linux64.sh#L43

Please upload the resulting AppImage to GitHub Releases, thank you.

**Comment by JaviBonilla** [comment]
Hi @probonopd 

I cannot directly upload the resulting AppImage since Surf is a tool to build multi-platform simulators, so it can be used by anyone to build their own apps. It is still under development, but there is more information at https://ciemat-psa.gitlab.io/surf-simulator/. There are also some under development example simulators built using Surf at https://ciemat-psa.gitlab.io/surf-simulator/portfolio/.
